### ISSUE TITLE
rich text message block results in run time error invalid_blocks

### ISSUE THREAD

**Issue by marvinatorrr** [stoiveyp/Slack.NetStandard#100]
```
var message = new Message
{
    Blocks = new List<IMessageBlock>
    {
        new RichText()
        {
            
        }
    }
};
```

using rich text in blocks will result in error message `invalid_blocks` when sending message

**Comment by stoiveyp** [comment]
Hi @marvinatorrr - an empty rich text block will cause an error, as it has to have content.

Here's an example of a RichText block that will post italic text.
```csharp
new RichText
        {
            Elements = new List<IMessageElement>
            {
                new RichTextSection
                {
                    Elements = new List<RichTextElement>()
                    {
                        new TextElement
                        {
                            Text = "Hello World",
                            Style = new() { { "italic", true } }
                        }
                    }
                }
            }
        };
```

If you go to the Slack Block Kit Builder (link https://api.slack.com/tools/block-kit-builder) then you'll see a Rich Text section down the bottom that shows you the JSON equivalent so you can see how the pieces fit together.
