### ISSUE TITLE
Serialiization error when Slack returns an error response from Chat.Post

### ISSUE THREAD

**Issue by mapitman** [stoiveyp/Slack.NetStandard#60]
I'm getting some sort of error back from Slack, but when the library tries to deserialize the error response from Slack for a call to Chat.Post:

```
Exception_Type=JsonSerializationException
Exception_Message="Error converting value ''failed to match all allowed schemas [json-pointer:/blocks/0/text]'' to type 'Slack.NetStandard.WebApi.WebApiError'. Path 'errors[0]', line 1, position 117."
InnermostException_Type=ArgumentException
InnermostException_Message="Could not cast or convert from System.String to Slack.NetStandard.WebApi.WebApiError."
```

I'm not sure if there is a way to get the JSON of the response. Is there a setting somewhere that would allow me to see it?

**Comment by stoiveyp** [comment]
Hi @mapitman - I’ll take a look at fixing the serialisation over the weekend, but the error itself is the ‘failed to match all allowed schemas’ text in the message you’re getting.

It appears that either one of the values in the text block at the start is invalid or possibly some of the text in that block is too long.

As I say, I’ll leave this open and hopefully get a fix released soon.

**Comment by mapitman** [comment]
Oh, thanks for that bit of info. What's weird is the code works on one Slack workspace and fails on another. I made a change to an existing block. It is a Button and I added `Style = ButtonStyle.Primary`. That was the only change. I rolled my change back and it works fine now. 🤷‍♂️

**Comment by mapitman** [comment]
OK, now I see my issue. I have a `TextBlock`  where the text is too long. Nothing to do with the button style. I was testing with some different data and that was the cause.

**Comment by stoiveyp** [comment]
Glad you were able to track the issue down. I was able to reproduce the serialization problem you had and correct it in 3.8.0-beta3, which has just been published.
