### ISSUE TITLE
Is there a mistaken?

### ISSUE THREAD

**Issue by bbilginn** [stoiveyp/Slack.NetStandard#61]
Is it correct? `ShouldSerializeAttachments` value should be set from `Blocks?.Any()`

https://github.com/stoiveyp/Slack.NetStandard/blob/62764b82cb06ac2f18ba215023928ad22cc8895b/Slack.NetStandard/WebApi/Chat/MessageRequestBase.cs#L45

I think it should be `Attachments?.Any()` but I am not sure, let me know.
https://github.com/stoiveyp/Slack.NetStandard/blob/62764b82cb06ac2f18ba215023928ad22cc8895b/Slack.NetStandard/WebApi/Chat/MessageRequestBase.cs#L46

Thanks!

**Comment by stoiveyp** [comment]
Absolutely right - v3.9.1 has this corrected, thanks
