### ISSUE TITLE
Element "Option" is missing "description" property from Slack specifications

### ISSUE THREAD

**Issue by zzullick** [stoiveyp/Slack.NetStandard#62]
Hi, thanks for this great library. Just starting to use it and stumbled upon one issue.

I've found the `Option` element for radio buttons is missing the `description` property as supported by the Slack specification described @  [https://api.slack.com/reference/block-kit/composition-objects#option](https://api.slack.com/reference/block-kit/composition-objects#option).

Current `Option` representation in the library:
[https://api.slack.com/reference/block-kit/composition-objects#option](https://github.com/stoiveyp/Slack.NetStandard/blob/main/Slack.NetStandard/Messages/Elements/Option.cs)

**Comment by stoiveyp** [comment]
Good spot @zzullick - this has been fixed in 3.12.1 and 3.13.0-beta2 👍
