### ISSUE TITLE
`ViewState` object has incorrect types for some submission payloads

### ISSUE THREAD

**Issue by zzullick** [stoiveyp/Slack.NetStandard#64]
Hello again! I found an issue with some of the types for view submission payloads.

The object in question is [ElementValue](https://github.com/stoiveyp/Slack.NetStandard/blob/main/Slack.NetStandard/Objects/ElementValue.cs) which is used in [ViewState](https://github.com/stoiveyp/Slack.NetStandard/blob/main/Slack.NetStandard/Objects/ViewState.cs#L11).

Potential issues found
- Missing `selected_date` property
- Missing `selected_time` property
- `selected_conversations` property is `string` but should be an array of strings
- `selected_channels` property is `string` but should be an array of strings
- `selected_users` property is `string` but should be an array of strings

For reference, here is the same type from Slack Bolt TS to compare against.
- https://github.com/slackapi/bolt-js/blob/main/src/types/view/index.ts#L159
- https://github.com/slackapi/bolt-js/blob/23cc0e16494c22783222821ebff789cfdaabeebd/src/types/view/index.ts#L132

**Comment by stoiveyp** [comment]
These updates have been made in 3.13.0 and 3.14.0-beta1 👍
