### ISSUE TITLE
Thread safety issues with `HttpClient` and `BaseAddress`

### ISSUE THREAD

**Issue by zzullick** [stoiveyp/Slack.NetStandard#66]
As a followup to https://github.com/stoiveyp/Slack.NetStandard/issues/65

Thanks for the changes to the authorization header, working much better now! I did find one additional problem. I'm really sorry I didn't see this in the original issue to avoid double work. But the `HttpClient.BaseAddress` is being set which is another non-thread-safe setting. I think instead it may be better to use the fully-qualified absolute URLs when executing the individual API requests instead of using relative ones, or to construct the URLs with a base address in a different way.

Where base address is set
- https://github.com/stoiveyp/Slack.NetStandard/blob/main/Slack.NetStandard/SlackWebApiClient.cs#L111

**Comment by stoiveyp** [comment]
Cheers for this one - updated in 3.13.1 and 3.14.0-beta2
