### ISSUE TITLE
`UpdateMessageRequest` for `chat.update` is missing property for `attachments` and `file_ids`

### ISSUE THREAD

**Issue by zzullick** [stoiveyp/Slack.NetStandard#67]
The `UpdateMessageRequest` found is missing a property for `attachments` and `file_ids` as supported according to Slack API docs for corresponding method `chat.update`.

Current definition of `UpdateMessageRequest`
- https://github.com/stoiveyp/Slack.NetStandard/blob/main/Slack.NetStandard/WebApi/Chat/UpdateMessageRequest.cs

Slack API specifications for `chat.update`
- https://api.slack.com/methods/chat.update.

**Comment by stoiveyp** [comment]
Fixed in 3.13.2 and 3.14.0-beta3
