### ISSUE TITLE
Chat.Post returns an error "no_authed"

### ISSUE THREAD

**Issue by ahocquet** [stoiveyp/Slack.NetStandard#69]
Hello,

I have an issue with the method `Chat.Post()` since version 3.13.0 up to 3.14.0-b4. It now fails with the error code "not_authed" whereas the same code works with version 3.12.1.

I set the Bearer token in the HTTP headers as such : 
![image](https://user-images.githubusercontent.com/1451308/173042829-e0af9ace-b181-4dd8-8117-28e59f5d4280.png)

Is there a new method to set the bot user token to post chat messages ?

Thanks,

Anthony

**Comment by stevenpears-bjss** [comment]
Thanks for raising this Anthony - there was a change made to the way we used the client internally to the library and it looks like this use case slipped through testing.

Let me pick this up as these versions weren't expected to be breaking changes and I'd rather fix the library than have you change your code for no reason 👍

**Comment by stoiveyp** [comment]
@ahocquet I've just released 3.13.4 and 3.14.0-beta5
Please let me know if these versions fix the issue you found
https://www.nuget.org/packages/Slack.NetStandard/3.13.4

**Comment by ahocquet** [comment]
I've upgraded to version 3.13.4 and the problem is now gone! Thanks a lot for your help. 👍🙏
