### ISSUE TITLE
`PayloadAction` has wrong types for array responses from Slack

### ISSUE THREAD

**Issue by lusis** [stoiveyp/Slack.NetStandard#75]
Hi there!
Great library and we love it. Thank you so much for maintaining it.

We ran into an issue with some interaction payloads that boils down to what was reported in #64 

In this case the `PayloadAction` here https://github.com/stoiveyp/Slack.NetStandard/blob/fe3a1f9fdfeb42b2d23d9d3c447807242d776d95/Slack.NetStandard/Interaction/PayloadAction.cs

Thank you so much again for maintaining the library

**Comment by stoiveyp** [comment]
Thanks for raising this! Totally missed that the structure is also in the PayloadAction.
Just pushed a patch update so it's resolved in the latest version of the library 👍
