### ISSUE TITLE
Warning in response: `superfluous_charset`

### ISSUE THREAD

**Issue by tomer-amir** [stoiveyp/Slack.NetStandard#77]
While sending most API calls were getting the following errors in the response:

```json
{
    "ok": true,
    // ...
    "warning": "superfluous_charset",
    "response_metadata": {
        "warnings": [
            "superfluous_charset"
        ]
    }
}
```

Found the following similar issue online in the python SDK: https://github.com/slackapi/python-slack-sdk/issues/692
apparently, this is caused by sending `utf-8` in the content type header:

```
Content-Type: application/json; charset=utf-8
```

**Comment by stoiveyp** [comment]
Thanks for raising this @tomer-amir. The issue has been resolved in v5.1.3
