### ISSUE TITLE
Sending RichText messages invalid_blocks error

### ISSUE THREAD

**Issue by AlesDo** [stoiveyp/Slack.NetStandard#90]
I am facing a problem sending a message containing a rich text block. I get the error `invalid_blocks`. This happens using the following basic sample..

```CSharp
var slackWebApiClient = new SlackWebApiClient(Environment.GetEnvironmentVariable("SLACK_BOT_TOKEN"));

var richText = new RichText(
    new RichTextSection()
    {
        Elements = new List<RichTextElement>()
        {
            new TextElement()
            {
                Text = "Hello Rich Text"
            } 
        }
    });
var blocks = [richText];
var postMessageRequest = new PostMessageRequest()
{
    Channel = "<ValidChannelID>", 
    Text = "Hello From API",
    Blocks = blocks
};
var response =await slackWebApiClient.Chat.Post(postMessageRequest);
```

Am I doing something wrong or this is not supported?

**Comment by stoiveyp** [comment]
Morning @AlesDo - I'm at work right now so I can't replicate the issue for a little while.

when you look at the response object - is there a pointer returned with the error messager (like `/blocks[0]...`) that could help us narrow down the problem? The example you sent works in the Block Kit Builder so just seeing if there's more help coming from Slack until I can try and recreate it

**Comment by AlesDo** [comment]
Hi @stoiveyp !

Thanks for your quick reply.
The pointer returned is: `must provide a string [json-pointer:/blocks/0/elements/0/elements/0/type]`.
It looks like it is a serialization issue that the type is not set for elements. it is set to null if I serialize the `PostMessageReaquest` using `JsonConvert.SerializeObject`.
Here is the output from serializing the request:
```JSON
{
  "mrkdwn": false,
  "channel": "U06EE5LP7Q9",
  "blocks": [
    {
      "type": "rich_text",
      "block_id": "d2ff47786b264d7389c67a5695a587a0",
      "elements": [
        {
          "type": "rich_text_section",
          "elements": [
            {
              "text": "Hello World",
              "type": null
            }
          ]
        }
      ]
    }
  ],
  "text": "Hello from slack app!!!!!",
  "parse": "none"
}
```

**Comment by stoiveyp** [comment]
Oh! Yeah that's clearly wrong. I'll get a new test written and fix it once my working day is done. Apologies and thanks for raising it 👍

**Comment by stoiveyp** [comment]
This should now be fixed in v8.2.1 - please let me know 👍

**Comment by AlesDo** [comment]
Yes now it works. Thanks for the quick fix.
There is just one detail more. If you don't provide the `BlockId` on the rich text block it serializes to `null` which again cause an error. `must provide a string [json-pointer:/blocks/0/block_id]`. It should not be omitted if it is not specified since it is an optional field https://api.slack.com/reference/block-kit/blocks#rich_fields

**Comment by stoiveyp** [comment]
v9.0.0 onward has Rich Text block_id set to optional
